#!/usr/bin/env python3
"""
AI Analytics Feature Demo
Demonstrates the powerful AI-driven analytics capabilities
"""

from agentic_graphs import AutonomousGraphSystem
import json


def demo_1_analytics_only():
    """Demo 1: Run analytics without visualization"""
    print("\n" + "="*70)
    print("DEMO 1: AI Analytics Only")
    print("="*70)
    print("\nRun comprehensive AI analytics on your data to extract insights,")
    print("detect patterns, identify anomalies, and get recommendations.")
    print()

    system = AutonomousGraphSystem()

    # Run analytics
    report = system.run_analytics(
        'data/3d_scatter_sample.csv',
        export_path='examples/demo_analytics.json'
    )

    print("\n✅ Analytics complete! Key insights:")
    for i, finding in enumerate(report.key_findings[:3], 1):
        print(f"\n  {i}. {finding}")


def demo_2_viz_with_analytics():
    """Demo 2: Generate visualization with AI analytics"""
    print("\n" + "="*70)
    print("DEMO 2: Visualization + AI Analytics")
    print("="*70)
    print("\nGenerate beautiful 3D visualizations AND get comprehensive")
    print("AI-powered insights in one step.")
    print()

    system = AutonomousGraphSystem()

    # Generate viz with analytics
    fig, report = system.generate_with_analytics(
        'data/network_sample.csv',
        output_path='examples/demo_network_with_analytics.html',
        show=False
    )

    print("\n✅ Visualization and analytics complete!")
    print(f"   Visualization: examples/demo_network_with_analytics.html")
    print(f"   Analytics: examples/demo_network_with_analytics.analytics.json")

    print("\n📊 Analytics Summary:")
    print(f"   Total Insights: {len(report.insights)}")
    print(f"   Patterns: {len(report.patterns)}")
    print(f"   Trends: {len(report.trends)}")
    print(f"   Recommendations: {len(report.recommendations)}")


def demo_3_explore_insights():
    """Demo 3: Explore detailed insights"""
    print("\n" + "="*70)
    print("DEMO 3: Exploring AI Insights")
    print("="*70)
    print("\nDive deep into the insights generated by the AI analytics engine.")
    print()

    system = AutonomousGraphSystem(verbose=False)

    report = system.run_analytics('data/3d_scatter_sample.csv')

    print("\n📊 Data Summary:")
    for key, value in report.data_summary.items():
        print(f"   {key}: {value}")

    print("\n🔍 Detected Patterns:")
    for pattern in report.patterns:
        print(f"   • {pattern}")

    print("\n📈 Identified Trends:")
    for trend in report.trends:
        print(f"   • {trend}")

    print("\n💡 AI Recommendations:")
    for i, rec in enumerate(report.recommendations, 1):
        print(f"   {i}. {rec}")

    print("\n📝 Natural Language Summary:")
    print(f"   {report.natural_language_summary}")


def demo_4_insight_categories():
    """Demo 4: Insights by category"""
    print("\n" + "="*70)
    print("DEMO 4: Insights by Category")
    print("="*70)
    print("\nThe AI categorizes insights for better understanding.")
    print()

    system = AutonomousGraphSystem(verbose=False)

    report = system.run_analytics('data/3d_scatter_sample.csv')

    categories = {}
    for insight in report.insights:
        if insight.category not in categories:
            categories[insight.category] = []
        categories[insight.category].append(insight)

    for category, insights in categories.items():
        print(f"\n📌 {category.upper()} ({len(insights)} insights):")
        for insight in insights:
            print(f"\n   Title: {insight.title}")
            print(f"   Description: {insight.description}")
            print(f"   Confidence: {insight.confidence:.0%}")
            print(f"   Severity: {insight.severity}")
            if insight.recommendation:
                print(f"   Recommendation: {insight.recommendation}")


def demo_5_json_export():
    """Demo 5: Working with exported JSON"""
    print("\n" + "="*70)
    print("DEMO 5: Working with JSON Export")
    print("="*70)
    print("\nAnalytics reports can be exported to JSON for further processing.")
    print()

    system = AutonomousGraphSystem(verbose=False)

    system.run_analytics(
        'data/network_sample.csv',
        export_path='examples/demo_network_analytics.json'
    )

    # Load and explore the JSON
    with open('examples/demo_network_analytics.json') as f:
        data = json.load(f)

    print(f"\n✅ Analytics exported to JSON")
    print(f"\nJSON structure:")
    for key in data.keys():
        print(f"   • {key}")

    print(f"\nExample: First insight")
    if data['insights']:
        insight = data['insights'][0]
        print(f"   Category: {insight['category']}")
        print(f"   Title: {insight['title']}")
        print(f"   Confidence: {insight['confidence']:.0%}")


def main():
    """Run all demos"""
    print("="*70)
    print("  🤖 AI-POWERED GRAPH ANALYTICS - FEATURE DEMO")
    print("="*70)
    print("\nThis demo showcases the AI analytics capabilities that provide")
    print("intelligent insights, pattern detection, and recommendations.")

    input("\nPress Enter to start Demo 1...")
    demo_1_analytics_only()

    input("\n\nPress Enter for Demo 2...")
    demo_2_viz_with_analytics()

    input("\n\nPress Enter for Demo 3...")
    demo_3_explore_insights()

    input("\n\nPress Enter for Demo 4...")
    demo_4_insight_categories()

    input("\n\nPress Enter for Demo 5...")
    demo_5_json_export()

    print("\n" + "="*70)
    print("  ✅ ALL DEMOS COMPLETE!")
    print("="*70)

    print("\n💡 Try these CLI commands:")
    print("   # Analytics only")
    print("   python -m agentic_graphs.cli data.csv --analytics-only")
    print()
    print("   # Visualization + Analytics")
    print("   python -m agentic_graphs.cli data.csv --analytics")
    print()
    print("   # Export analytics to JSON")
    print("   python -m agentic_graphs.cli data.csv --analytics-only --export-analytics report.json")

    print("\n" + "="*70)


if __name__ == '__main__':
    main()
